### ISSUE TITLE
Cannot open device - Tinker Board S

### ISSUE THREAD

**Issue by sobrinho** [linux-rockchip/rkflashtool#9]
<img width="863" alt="screen shot 2018-10-08 at 19 44 57" src="https://user-images.githubusercontent.com/26460/46637467-aa412700-cb32-11e8-8481-2f4bd4122c78.png">

```diff
diff --git a/rkflashtool.c b/rkflashtool.c
index 7287e8f..b9ba0af 100644
--- a/rkflashtool.c
+++ b/rkflashtool.c
@@ -314,6 +314,8 @@ int main(int argc, char **argv) {
         if (h) {
             info("Detected %s...\n", ppid->name);
             break;
+        } else {
+            info("Ignored %s...\n", ppid->name);
         }
         ppid++;
     }
```

```
λ ./rkflashtool v
rkflashtool: info: rkflashtool v5.2
rkflashtool: info: Ignored RK2818...
rkflashtool: info: Ignored RK2918...
rkflashtool: info: Ignored RK2928...
rkflashtool: info: Ignored RK3026...
rkflashtool: info: Ignored RK3066...
rkflashtool: info: Ignored RK3168...
rkflashtool: info: Ignored RK3036...
rkflashtool: info: Ignored RK3066B...
rkflashtool: info: Ignored RK3188...
rkflashtool: info: Ignored RK312X...
rkflashtool: info: Ignored RK3126...
rkflashtool: info: Ignored RK3288...
rkflashtool: info: Ignored RK322X...
rkflashtool: info: Ignored RK3368...
rkflashtool: fatal: cannot open device
```

**Comment by sobrinho** [comment]
Same behavior ou Ubuntu 18.04.

**Comment by julienchauveau** [comment]
Hello Gabriel,

Have you tried to put the jumper in eMMC recovery mode?

![image](https://fossbytes.com/wp-content/uploads/2018/01/asus-tinker-board-s-parts.jpg)

Your Product ID (0x0006) means your device is in mode **usb mass storage** (UMS).

To use `rkflashtool`, you need to put your device in **loader** mode.

If you have Android installed on your device, you can use `adb` to go into loader mode:

    adb reboot loader

or

    adb reboot bootloader

**Comment by sobrinho** [comment]
Ops! I was trying `adb reboot bootloader` but I'm using an Android image.

Anyway, switching the jumper to recovery made it, thanks for your time!
